### ISSUE TITLE
Spyke and Pagination

### ISSUE THREAD

**Issue by thiagocifani** [balvig/spyke#11]
How is the best way to use pagination such as Kaminari with spyke?

**Comment by balvig** [comment]
It will depend on what metadata your API returns, but in a current proejct we get back "total_count" and "per_page", which is exactly what Kaminari needs to create pagination links.

We've then created a concern to include in resources that support pagination:

```ruby
module Pagination
  extend ActiveSupport::Concern

  module ClassMethods
    def page(number)
      result = where(page: number)
      Kaminari.paginate_array(result, total_count: result.metadata[:total_count]).page(number).per(result.metadata[:per_page])
    end
  end
end
```

This is allows us to go


```ruby
@posts = Post.page(3)
```

and then

```erb
<%= render @posts %>
<%= paginate @posts %>
```

as usual.

**Comment by thiagocifani** [comment]
In the server side, how should be your render? do you have pagination there too?

**Comment by thiagocifani** [comment]
What does result metadata means? are you using api-pagination gem or returning in the header?

**Comment by balvig** [comment]
Metadata is simply a method on Spyke collections that allows you to access extra info returned by the API in addition to the actual data of the records (See [here](https://github.com/balvig/spyke/blob/fda4c2f2f44a3c6a697ee390b461d525a4934156/test/support/api.rb#L7) and [here](https://github.com/balvig/spyke/blob/269a1f66ad12967db61cf6d7abf782a39bd61292/test/relation_test.rb#L6-L12))

In our case the pagination info is returned along with the JSON, but you could also use headers if you wanted. It's up to you to pack them inside the hash that's passed to Spyke via Faraday (ie `{ data: [], metadata: {}, errors: {} }`).

For example:

```ruby
class JSONParser < Faraday::Response::Middleware
  def parse(body)
    json = MultiJson.load(body, symbolize_keys: true)
    {
      data: json[:result],
      metadata: { total_count: env[:response_headers]['X-Total-Count'],
      errors: json[:errors]
    }
end
```

The total count can then be accessed from your app like this:

```ruby
Post.all.metadata[:total_count]
```

Hope that makes sense!

**Comment by thiagocifani** [comment]
How do you return metadata on your api controller, could you give me some example?

**Comment by balvig** [comment]
It's completely up to how you're designing the API, using rails, jbuilder, sinatra, something else entirely! :grin: 

A simple example would be:

```ruby
def index
  render json: { result: @posts, extra: { total_count: Post.count, ... }  }
end
```

**Comment by thiagocifani** [comment]
Hey man, I totally got it. I was thinking in paginate the pagination you know. I am not comfortable dealing with all data in the client side. Do you know what I mean?

**Comment by balvig** [comment]
Hehe, yep, whenever possible I prefer to just stick to good old ActiveRecord :smile: 
Glad you figured it out, good luck! :space_invader:

**Comment by toddmazierski** [comment]
Hi all,

I just wanted to share a library that might be useful to some, [Spyke::Kaminari](https://github.com/generalassembly/spyke-kaminari). It makes Spyke models aware of APIs that return [pagination headers](https://github.com/generalassembly/spyke-kaminari/blob/3674c98990c2d23c7b1b7548ecfd2edae7090056/lib/spyke/kaminari.rb#L4-L12), like those from the [Grape::Kaminari](https://github.com/monterail/grape-kaminari) gem.

A key part of this library is how `Spyke::Kaminari::Relation` is returned for pagination-enabled models (instead of `Spyke::Relation`). Here is [the :monkey_face: patch](https://github.com/generalassembly/spyke-kaminari/blob/3674c98990c2d23c7b1b7548ecfd2edae7090056/lib/spyke/kaminari/scopes.rb#L12-L16) that achieves this. I chose this path so models _without_ the module included [remain unaffected](https://github.com/generalassembly/spyke-kaminari/blob/3674c98990c2d23c7b1b7548ecfd2edae7090056/spec/lib/spyke/kaminari/scopes_spec.rb#L81-L102). A couple design questions for you all:

  * Is returning a custom relation class with pagination features sensible?
  * If yes, is this patch OK, or could some kind of relation "plugin" system be developed?

My overall goal is that new features and refactors in Spyke don't cause Spyke::Kaminari to break. Any feedback you have would be most appreciated! Thank you.

**Comment by toddmazierski** [comment]
If desired, please feel free to open Issues or Pull Requests in the [Spyke::Kaminari](https://github.com/generalassembly/spyke-kaminari) library itself, and thanks again!

**Comment by balvig** [comment]
@toddmazierski this is awesome!! Super stoked to see something being built on Spyke! :tada: 
Re your question, not sure what the best approach is, but if you're worried about overriding and future changes, one way might be to simply add the pagination methods as class methods? 

Will try to show in a PR, haven't completely thought it through, but this way at least you don't have to redefine `all`.

**Comment by chriso0710** [comment]
Just saw this thread.

I would like to use Spyke for handling a REST API which returns XML data with the pagination data in the XML body, not in the header.

```xml
<time_entries total_count="12706" offset="0" limit="25" type="array">
    <time_entry>
        ...    
    </time_entry>
    ...
</time_entries>
````

I am not sure if Spyke::Kaminari is able to help me with this.
What would be the best approach to get all pages and/or to get all model objects with Model.all?

Thanks
Christian

**Comment by balvig** [comment]
@chriso0710 my guess is you would need to do something similar to https://github.com/generalassembly/spyke-kaminari/blob/master/lib/spyke/kaminari/header_parser.rb#L3-L12, except you would be parsing the XML itself, instead of the headers to get the values that Kaminari requires!
