### ISSUE TITLE
Params with namespace concat

### ISSUE THREAD

**Issue by thiagocifani** [balvig/spyke#12]
Hi, I have the following model.

```ruby
class Test::Occurrence < Spyke::Base
  uri '/occurrences/:id'
end

```

my params has the model module as a key add to my model name, anyway to override this behavior?

params = { test_occurrrence}  I would prefer occurrence only.

**Comment by balvig** [comment]
Not at the moment no... :( 

Makes sense to me though that you should be able to customise it! I'm thinking, since Spyke already had a `include_root_in_json ` method, being able to pass a string to that might be a good way to do it, ie:

```ruby
class Test::Occurrence < Spyke::Base
  include_root_in_json 'occurence'
end
```

Would you be interested in having a go at speccing/adding this feature to Spyke?
Places to look are:

- https://github.com/balvig/spyke/blob/master/lib/spyke/orm.rb#L16-L17
- https://github.com/balvig/spyke/blob/master/lib/spyke/orm.rb#L53
- https://github.com/balvig/spyke/blob/master/test/orm_test.rb#L122-L124
