### ISSUE TITLE
Trying to move away from Her but need the use_api method

### ISSUE THREAD

**Issue by amalagaura** [balvig/spyke#144]
I have a [Gem](https://github.com/amalagaura/camunda-workflow) which uses Her to access an API. I need to migrate off Her because their version of Faraday is just too old.

Because the gem is used by apps, it needs dynamic initialization of the models. So I [use the `use_api` method](https://github.com/amalagaura/camunda-workflow/blob/master/lib/camunda/model.rb#L11) which allows us to pass a lambda. 

Can I do the equivalent in Spyke? I see we have the `self.connection = Faraday.new` but I don't think my code will work because it is not dynamic enough. Any idea here?

**Comment by balvig** [comment]
Hey @amalagaura! Thanks for getting in touch.

I took a look at `Camunda::Model`, and being unfamiliar with the project I might have it wrong, but I assume the problem is that `self.connection = ` would get set first, and _then_ a user of the gem would use `Camunda::Workflow.configure`?

The following options came to mind:

1. Let calling `Camunda::Workflow.configure` also set `self.connection = ...`
2. Define your own `self.connection` method to instantiate (and cache) Faraday the first time `connection` is called
3. Add lambda support to `self.connection =` in Spyke 😉 

There are probably other approaches, but these were the ones I could think of off the top of my head. 😊

**Comment by amalagaura** [comment]
OK thanks for this response. I am working through with the first option and have made progress. Still working on the migration but it looks promising!
