### ISSUE TITLE
Instrumentation

### ISSUE THREAD

**Issue by gottfrois** [balvig/spyke#23]
Hey,

I have quite a complex scenario using http caching to avoid unnecessary queries to my API if the content is still fresh. But to make it simple, it seems that the spyke requests logger logs requests when it should not.

Here is the interesting part of my log server:

```
HTTP Cache: [GET /api/v1/contents/v3_shared_author_footer_links?locale=en-EU] fresh
  Spyke (0.7ms)  GET http://localhost:3001/api/v1/contents/v3_shared_author_footer_links?locale=en-EU [200]
```

As you can see, i'm trying to do a get request on `/api/v1/contents/v3_shared_author_footer_links` and my caching strategy is basically saying here "this content was not modified for the last 5 minutes, let me use the cache version I have for it".

And in fact, looking at my api server logs, there are no `GET` requests happening at this very moment. However the spyke logs shows that a request happened which is, by looking at the logs, not true :)

Let me know if you need more implementation details.

**Comment by balvig** [comment]
Ah yes, this happens because the caching takes place in Faraday, and Spyke has no knowledge of what goes on in there :smile:  

I realize that this can probably be a bit misleading now that you mention it, but I actually find it kinda useful to see the Spyke calls even when the http request itself is cached! As Spyke still needs to do parsing etc so I like to keep an eye on the time this takes (in your case 0.7ms) even for cached requests :sweat_smile: 

Would be nice if we could show "CACHED" or something like that a la ActiveRecord but I can't really think of a good way to get that information back from Faraday!

**Comment by balvig** [comment]
(btw I use the excellent logger found in https://github.com/yourkarma/faraday-conductivity when I want lower level Faraday info, can be useful in addition to the instrumentation for looking at caching etc)

**Comment by gottfrois** [comment]
Thanks for the explanation !
