### ISSUE TITLE
Should absolute uri's really be default?

### ISSUE THREAD

**Issue by jontebol** [balvig/spyke#25]
First of all, thanks for creating Spyke! I recently switched from Her for various reasons, and although Spyke is a bit "young" yet (and under very active development! :)), it's a nice and lean bit of software, and it's small enough that I can actually understand how it works. :+1: 

Ok, to my question:
Spyke generates absolute uri's by default. This causes some confusion becase Faraday will remove the url_prefix if passed an absolute uri. That's to be expected of Faraday of course, but I don't see why Spyke should use absolute uris by default.

It means that if I config Spyke with the following uri:
````
Spyke::Config.connection = Faraday.new(url: 'http://api.com/api/v2') do |c|
...
end
````
It will completely ignore the "api/v2" part by default, unless I set all my model+association uris to be non-absolute (just remove the slash in the beginning), which means I have no use for the defaults generated by Spyke.

So my suggestion is simple, just use relative uris by default.

I think this is probably also the cause of #20.

**Comment by thibaudgg** [comment]
:+1:

**Comment by balvig** [comment]
@jontebol thanks so much for the kind words! Made me genuinely happy, one of the reasons I started this project was that I figured if I wrote it myself, at least _I_ would know how it works. Turns out that's not always true as the project grows :stuck_out_tongue_closed_eyes:, but am thrilled that it at least seems the code is somewhat approachable :smile: 

The issues you posted are not a pain at all, but very welcome! I will address them one at a time.

So first of all...oh my god I did know that that was how Faraday worked! Thanks so much for letting me know, that solves not only #25 but I think addresses @gottfrois use case in https://github.com/balvig/spyke/pull/19#issuecomment-75379269

I've switched to relative paths in https://github.com/balvig/spyke/pull/29, will release a new gem version a little later today :+1:
