### ISSUE TITLE
Make save, save! and create behave like ActiveRecord

### ISSUE THREAD

**Issue by jontebol** [balvig/spyke#27]
My third suggestion for today, hope you don't think I'm a pain in the *... ;)

I'm building a client based on Spyke, and in my base class (which inherits from Spyke::Base) I've added the following:
````
    def self.create(attrs = {})
      instance = self.new(attrs)
      instance.save!
      return instance
    end

    def save
      errors.clear
      super
      return !errors.any?
    end

    def save!
      raise BlaBla::Error::ResourceInvalid, self.errors unless self.save
    end
```

This makes Spyke behave more like ActiveRecord, so that save returns true or false, while save! and create raise errors if validation failes.

I'm not suggesting you use this code, just that it might be a good idea to make Spyke behave more like ActiveRecord on those methods.

**Comment by balvig** [comment]
Sorry for not getting back to you about this sooner! :sweat_smile: 

The reason is that I haven't actually been able to make up my mind about how this should work... :cat: 
Since Spyke, thanks to ActiveModel, can also have validations added client side (using the usual `validates ...` methods), the `valid?`-check could in theory happen _before_ the request gets sent.

Your example suggests that you want this to work with errors returned from the API _after_ the request is made which somehow seems correct to me, but to avoid confusion maybe need to figure out what to do with client side validations (maybe even disable them?) first. 

Am currently at a stage in an API-based project using Spyke were how to handle validations is being worked out so probably that will surface some answers. Meanwhile would love to hear more about how your own version is working out as the project moves along! :smile: 

(Btw, I assume you are referring to `create!` rather than `create`? If I remember correctly AR only raises exceptions on invalid records when using the "bang" version)

**Comment by jontebol** [comment]
You are right about my use case. I haven't planned on using any client side validations, although I'm sure there are use cases where they would be nice to have. But does it really matter to this discussion? The way Spyke works it already behaves similarly for errors from the API and locally, right? In both cases it adds errors to the model, so what would be the difference? "valid?" would always be a local call in any case (right?), so that way you could check your client side validations first if you like. And the way I implemented save, it would clear any errors before trying again so you could easily do both.

About how AR works... It's funny because I was sure it was as you say (that "bang"-versions raise errors), so I checked it out before posting this issue (because I wanted my client-lib to be as AR-like as possible, that's how I even discovered this in the first place) and to my surprise found that there was no "create!"-method and that the regular "create"-method raised errors. Now however, when I try to find confirmation of this, I realize I must have been either drunk or mad from sleep depravation when I looked it up last time. Of course that's how AR works!! :P Or else, I decided that's how I wanted my own client-lib to behave and (in my crazy state of mind that I was obviously in) transposed that behaviour onto AR. Oh, well, the original intent behind this issue still holds. :) So in case someone else finds this and would like to copy my code, here's the updated versionen that works similiar to AR:

```Ruby
    def self.create!(attrs = {})
      instance = self.new(attrs)
      instance.save!
      return instance
    end

    def self.create(attrs = {})
      instance = self.new(attrs)
      instance.save
      return instance
    end

    def save
      errors.clear
      super
      return !errors.any?
    end

    def save!
      raise BlaBla::Error::ResourceInvalid, self.errors unless self.save
    end
```

**Comment by balvig** [comment]
> But does it really matter to this discussion? The way Spyke works it already behaves similarly for errors from the API and locally, right? In both cases it adds errors to the model, so what would be the difference? "valid?" would always be a local call in any case (right?), so that way you could check your client side validations first if you like

Heh, yeh, but I guess if I have validations set on the client too, I would sort of expect `create!` to raise an exception if _they_ fail too, and so at that point it's start to get a bit unclear whether it's one set of validations or the other that triggers the behavior :sweat_smile: 

In any case probably the main problem is I'm not currently using validations myself at the moment, maybe once I start doing that I will be able to see things more clearly :grin:

**Comment by jontebol** [comment]
Absolutely, just off the top of my head I would expect local validations to run first, then if they are successful, try to create the remote resource. On the other hand, maybe one would want to have those steps be explicit. I see what you mean by thinking it through with real use-cases... :) Feel free to close this issue if you want as it was just a general suggestion.

**Comment by balvig** [comment]
Thanks for the comments though! :smile: (he said, pretending his reply wasn't more than half a year late)
Will keep an eye on this if I encounter it in one of our projects :rocket:

**Comment by jontebol** [comment]
:) :+1:

**Comment by romikoops** [comment]
+1 for create! and save! methods implementation. I am going to use the gem instead of Her in my open source project Howitzer https://github.com/strongqa/howitzer for acceptance testing. There is amazing well known FactoryGirl gem for fast test data preparation. With current trend, Service Oriented Architecture, you can not integrate your tests to specific service or application. You have to test all services as single application at the same time. Fortunately we can use FactoryGirl + Spyke as replacement of ActiveRecord. Only one limitation, it relies on missing create! method. Of course it is possible to implement it like @jontebo did. But it will be nice to have in the gem.

**Comment by balvig** [comment]
@romikoops glad to hear Spyke is useful to you! ⭐ 

To be honest I still haven't found a good answer to the concerns I raised above... 😓  perhaps you can provide further input?

Also super interested to know how you will be using FactoryGirl with Spyke, since as you know Spyke doesn't actually create any records in the db (`FactoryGirl.create(...)` would send http requests I guess?)

**Comment by romikoops** [comment]
https://github.com/strongqa/howitzer_example_rspec/commit/54bbc936edccb4a1cf26f3119ab5f60a679d0abe
