### ISSUE TITLE
Faraday::Error: :json is not registered on Faraday::Request

### ISSUE THREAD

**Issue by jontebol** [balvig/spyke#31]
I actually found this a while back, but I haven't reported it yet. It's something that I believe could be quite annoying to new users:

I the readme, you'r example configuration is:

```Ruby
Spyke::Config.connection = Faraday.new(url: 'http://api.com') do |c|
  c.request   :json
  c.use       JSONParser
  c.adapter   Faraday.default_adapter
end
```

That won't work out of the box though, becase you'll get the error message in the title since the :json request middleware is actually not a part of the ```faraday``` gem, but of the ```faraday_middleware``` gem, which means you should either change the example config, or add ```faraday_middleware``` as a runtime dependency.

**Comment by jontebol** [comment]
Geez, I just looked at https://github.com/balvig/spyke/blob/master/spyke.gemspec and saw that you do have ```faraday_middleware``` listed as a depencency. :P So, I guess it just needs to be required somewhere then. :)

**Comment by balvig** [comment]
Excellent catch, thanks so much!
I think I at first didn't want to add it since prob not everyone uses JSON, but for sheer ease of getting set up makes sense to have it (especially when the examples otherwise don't work!! :sweat_smile: )

Fixed: https://github.com/balvig/spyke/commit/7b4f1a76509b9e7ba1968900ce2f913fe9c93812
