### ISSUE TITLE
to_sym in add_errors_to_model causes translation error

### ISSUE THREAD

**Issue by LucasCioffi** [balvig/spyke#80]
Hello, great gem!

I can use a bit of help, because I'm seeing this error related to my `Measurement` model:
`translation missing: en.activemodel.errors.models.app_client/measurement.attributes.base`

The error goes away when I make this change:
```
      def add_errors_to_model(errors_hash)
        errors_hash.each do |field, field_errors|
          field_errors.each do |attributes|
            error_name = attributes.delete(:error).to_sym # this causes the error
            # error_name = attributes.delete(:error) # no error
            errors.add(field.to_sym, error_name, attributes.symbolize_keys)
          end
        end
      end
```

The error message is coming from our other internal app which is using [Grape](https://github.com/ruby-grape/grape) to format the error messages.

Any help is greatly appreciated!

**Comment by balvig** [comment]
Hey there @LucasCioffi! 👋  Could you maybe provide a bit more context, ie what does the `Measurement` model look like, and what JSON is it receiving?

**Comment by LucasCioffi** [comment]
Hi @balvig, the app using Spyke is sending requests to another one of our apps which is using Grape.  

The problem occurs when the app (which is using Grape) sends this (expected) response with a 409 status: 
```
{
  "errors": {
    "base": [
      {
        "error": "Measurement not created.  Details: Validation failed: User attempted to create duplicate measurement"
      }
    ]
  }
}
```
Then the translation error occurs.

`measurement.rb` looks like this:
```
module AppNameClient
  class Measurement < Spyke::Base
    include SpykeActsAsTenant
    include_root_in_json true

    belongs_to :episode
    belongs_to :measurement_type
  end
end
```

**Comment by LucasCioffi** [comment]
Hi @balvig Was this the info that you were looking for?

**Comment by balvig** [comment]
@LucasCioffi hmm yes, it's a tricky one...the reason for the `to_sym` part is so that you can set up translations client side for errors. 

Spyke expects to receive translation keys like `too_short` that it can then look up itself, rather than the plain text example "Measurement not created" you have.

You can see the format it expects here:

https://github.com/balvig/spyke/blob/1438f7171f4317e373e4521a3083707bbc2a912f/test/orm_test.rb#L87-L93

and here: https://github.com/balvig/spyke#api-side-validations

Not sure if there's a good way to make it also work when plain text is returned...any ideas?

One way to "fix it" I guess would be to change your server to return a translation key instead of text! 😓

**Comment by LucasCioffi** [comment]
Thanks, @balvig.  We can work with this.

**Comment by balvig** [comment]
Related: https://github.com/balvig/spyke/pull/91 😅
