### ISSUE TITLE
Spyke doesn't find the id field

### ISSUE THREAD

**Issue by simmogs** [balvig/spyke#96]
For some reason, the id field is passed into the instance from the JSON data. I'm using the standard JSONParser from the README. Everything else is pretty standard.

    class Lunch::Company < Spyke::Base
      self.connection = Faraday.new(url: 'http://localhost:3000/api') do |c|
        c.request   :json
        c.use       JSONParser
        c.adapter   Faraday.default_adapter
        c.headers['Authorization'] = MyApi.generate_credentials
      end

      include_root_in_json :company
      attributes :name, :accounting_code, :id
    end

When I get the result back it's as follows:

    #<Lunch::Company(companies/(:id)) id: nil company: {"id"=>19, "name"=>"A test company", "accounting_code"=>"TEST01"}>

I was expecting the id field to be populated and it's causing problems that it isn't. The data coming includes the JSON root. I've tried variously setting it to true, false and :company as above. I'm probably missing a step but I don't know what it is.

    class JSONParser < Faraday::Response::Middleware
      def parse(body)
        json = MultiJson.load(body, symbolize_keys: true)

        errors = json.delete(:errors) || {}
        metadata = json.delete(:metadata) || {}
        {
          data: json,
          metadata: metadata,
          errors: errors
        }
      rescue MultiJson::ParseError => exception
        { errors: { base: [ error: exception.message ] } }
      end
    end

**Comment by balvig** [comment]
@simmogs I _think_ maybe it might be related to this:

```ruby
attributes :name, :accounting_code, :id
```

The primary key is given special treatment since it needs to be user in finder methods etc, probably adding it to `attributes` is "demoting" it to a "plain attribute".

It is my _guess_ that removing it from the list of attributes will bring things into working order!

**Comment by simmogs** [comment]
I've already tried that and it doesn't make any difference.

**Comment by balvig** [comment]
@simmogs is there any chance you could submit a spec that simulates the problem?

**Comment by dbourguignon** [comment]
If I understand correctly, the issue is with having on the client side a namespaced model (`Lunch::Company`)
When posting to the API endpoint, this will be serialised as `{id: 123, lunch_company: {……}}`

But on the server side, this model is not in namespace. 

@simmogs The easiest fix in this case if you can change the server side is to do something like:

```ruby
  def company_params
    params.require(:lunch_company).permit(:accounting_code, :name, :use_ssl)
  end
```

@balvig the problem in this case is that if we override the root by : `include_root_in_json :company`for instance, then the root is use for all call and the find do not work as expected

**Comment by balvig** [comment]
@simmogs Hope on way or the other your problem was resolved (thanks for chiming in @dbourguignon!). Otherwise feel free to submit a spec or something so can take a closer look. 🙏
